include: package:lints/recommended.yaml

linter:
  rules:
    await_only_futures: true

analyzer:
  errors:
    invalid_override_of_non_virtual_member: error
    invalid_use_of_protected_member: error
    depend_on_referenced_packages: error