name: packages-smvp_dart-running_unit_tests
run-name: ${{ github.actor }} - packages-smvp_dart-running_unit_tests
on:
  push:
  workflow_dispatch:
env:
  flutter_channel: stable
  working_directory: packages/smvp_dart
jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.flutter_channel }}
      - run: flutter pub get
        working-directory: ${{ env.working_directory }}
      - run: flutter test
        working-directory: ${{ env.working_directory }}